### ISSUE TITLE
Where to access the paper?

### ISSUE THREAD

**Issue by soenmezanil** [fzh0917/SparseTT#1]
Dear authors, thank you for publishing the work. Could you please point out where I can access the paper? Thanks in advance!

**Comment by fzh0917** [comment]
> Dear authors, thank you for publishing the work. Could you please point out where I can access the paper? Thanks in advance!

Sorry for the late reply. The paper is available at: [https://arxiv.org/abs/2205.03776](https://arxiv.org/abs/2205.03776).
