### ISSUE TITLE
恢复训练

### ISSUE THREAD

**Issue by C-C-Y** [fzh0917/SparseTT#13]
你好，我训练途中中断了只能从头开始训练么，可以加载已训练的部分恢复训练么

**Comment by marico2020** [comment]
可以的 在--resume设置断点的Epoch数

**Comment by C-C-Y** [comment]
> 可以的 在--resume设置断点的Epoch数

好的，谢谢你

**Comment by ElliottZhen** [comment]
@marico2020 请问你复现SparseTT了吗，结果差别大吗，

**Comment by ElliottZhen** [comment]
@C-C-Y 请问你复现了吗，结果差别大吗

**Comment by C-C-Y** [comment]
> @C-C-Y 请问你复现了吗，结果差别大吗

每个指标在0.5-1误差内，例如AO我测的为68.6，多测几个epoch，不一定最后一个结果最好

**Comment by ElliottZhen** [comment]
好的，纠结这个精度问题好久了，非常感谢你的解答，我多试试！



---原始邮件---
发件人: "Double ***@***.***&gt;
发送时间: 2023年4月28日(周五) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fzh0917/SparseTT] 恢复训练 (Issue #13)




  
@C-C-Y 请问你复现了吗，结果差别大吗
  
每个指标在0.5-1误差内，例如AO我测的为68.6，多测几个epoch，不一定最后一个结果最好

**Comment by wanzhen666** [comment]
你好，打扰了，我想请教一下，我用全部数据训练时候，家在数据及时候，VID和DET，这两个数据集识别的长度总是为0，我数据集路径应该没有问题，里边也有图片，然后会报一个ValueError的错误，a must be greater than 0 unless no samples are taken，我感觉是数据集读取的问题，这两个数据集之前没有了解过，请问你出现过这个问题吗？



---原始邮件---
发件人: "Double ***@***.***&gt;
发送时间: 2023年4月28日(周五) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fzh0917/SparseTT] 恢复训练 (Issue #13)




  
@C-C-Y 请问你复现了吗，结果差别大吗
  
每个指标在0.5-1误差内，例如AO我测的为68.6，多测几个epoch，不一定最后一个结果最好
