### ISSUE TITLE
Computation of sparse self-attention within decoder

### ISSUE THREAD

**Issue by davidyang180** [fzh0917/SparseTT#6]
Hi! After the attention value of top_k is extracted in the code, softmax is done after subtracting the maximum value. Will this lead to a low estimate of the final result of the attention map?
`attn_topk_softmax = torch.softmax(attn_topk - max_vals, dim=-1)`

**Comment by fzh0917** [comment]
No. 
$$\text{softmax}(x_i) = \frac{e^{x_i}}{e^{x_0} + e^{x_1} + \cdots + e^{x_{n-1}}} =  \frac{\frac{e^{x_i}}{e^{C}}}{\frac{e^{x_0} + e^{x_1} + \cdots + e^{x_{n-1}}}{e^{C}}} = \text{softmax}(x_i-C)$$. Thus, `attn_topk_softmax = torch.softmax(attn_topk - max_vals, dim=-1)` is equal to `attn_topk_softmax = torch.softmax(attn_topk, dim=-1)`.
Here is an example:
```Python
>>> a = torch.rand(1024,)
>>> b = torch.softmax(a, dim=0)
>>> c = torch.softmax(a - a.max(), dim=0)
>>> torch.equal(b, c)
True
```

**Comment by fzh0917** [comment]
The reason for subtracting the maximum values is to prevent the exponential calculation from overflowing. @davidyang180
