### ISSUE TITLE
About Sparse MHSA

### ISSUE THREAD

**Issue by ZiMo-Chen** [fzh0917/SparseTT#7]
How does "Sparse multi-head self-attention" compare to the original in terms of computation complexity, parameters, and GFlops

**Comment by fzh0917** [comment]
The theoretical computational complexity of sparse multi-head self-attention (SMSA) and naive multi-head self-attention (MSA) is the same, and the number of parameters too. Actually, MSA is a special case of SMSA.
However, the FLOPs of SMSA are significantly smaller than those of MSA. In this work, we did not strictly go for the specific values. If you want to know it, I recommend you use [thop](https://github.com/Lyken17/pytorch-OpCounter) or [ptflops](https://github.com/sovrasov/flops-counter.pytorch) to calculate it.

**Comment by ZiMo-Chen** [comment]
> 

Thank you for your reply!
